# Copyright (C) 2018  Kaiserpfalz-EDV Service, Roland T. Lichti
# This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
# This is free software, and you are welcome to redistribute it
# under certain conditions; type `show c' for details.

apiVersion: v1
kind: Template
metadata:
  name: wordpress-s2i
  labels:
    template: wordpress-s2i
  annotations:
    description: >-
      A Wordpress S2I builder. For more information please check
      https://github.com/klenkes74/openshift-wordpress/blob/master/README.md.
    iconClass: icon-apache
    openshift.io/display-name: Wordpress S2I Builder
    openshift.io/documentation-url: 'https://github.com/klenkes74/openshift-wordpress'
    openshift.io/long-description: >-
      This image is an S2I builder running on top of PHP with a predefined Wordpress
      Version.
    openshift.io/provider-display-name: 'Kaiserpfalz EDV-Service, Roland T. Lichti'
    openshift.io/support-url: 'https://www.kaiserpfalz-edv.de'
    tags: 'httpd,php,wordpress,cms'
    template.openshift.io/bindable: 'true'
parameters:
- name: 'WORDPRESS_VERSION'
  displayName: 'Wordpress Version'
  required: false
- name: 'WP_CLI_VERSION'
  displayName: 'Wordpress CLI Version'
  required: false
- name: 'PHP_BASE_IMAGE_VERSION'
  displayName: 'PHP Version to use'
  value: 'latest'
  required: true
- name: 'REPOSITORY'
  displayName: 'Git Repository'
  description: 'Git repository containing all site specific data'
  value: 'https://github.com/klenkes74/openshift-wordpress.git'
  required: true
- name: 'REPOSITORY_CONTEXTDIR'
  displayName: 'Context Directory'
  description: 'Directory within repository.'
  value: '/wordpress'
  required: true
- name: 'REPOSITORY_TAG'
  displayName: 'Git Tag'
  description: 'Tag inside the git repo to use.'
  value: 'master'
  required: true
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: wordpress-s2i
    labels:
      app: worpress
      template: wordpress-s2i
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    annotations:
      description: Defines the build of the generic wordpress base image
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      app: wordpress-s2i
      template: wordpress-s2i
    name: wordpress-s2i
  spec:
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
    completionDeadlineSeconds: 120
    successfulBuildsHistoryLimit: 2
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: 'wordpress-s2i:${WORDPRESS_VERSION}'
      imageLabels:
      - name: 'io.k8s.display-name'
        value: 'WordPress S2I Builder'
      - name: 'io.k8s.description'
        value: 'WordPress Application S2I Builder (based on Apache 2.4 and PHP 7.2 in Red Hat version ${PHP_BASE_IMAGE_VERSION}'
      - name: 'io.openshift.s2i.scripts-url'
        value: 'image:///usr/libexec/s2i'
      - name: 'io.s2i.scripts-url'
        value: 'image:///usr/libexec/s2i'
      - name: 'io.openshift.tags'
        value: 'builder,php,wordpress'
      - name: 'template'
        value: 'wordpress-s2i'
      - name: 'io.openshift.expose-services'
        value: '8080:http'
    source:
      git:
        uri: "${REPOSITORY}"
        ref: "${REPOSITORY_TAG}"
      contextDir: "${REPOSITORY_CONTEXTDIR}"
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: 'WORDPRESS_VERSION'
          value: '${WORDPRESS_VERSION}'
        - name: 'WP_CLI_VERSION'
          value: '${WP_CLI_VERSION}'
        from:
          kind: ImageStreamTag
          name: 'php72:${PHP_BASE_IMAGE_VERSION}'
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange